# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from messages/Injury.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Injury(genpy.Message):
  _md5sum = "ea36f64e92a1aa168772ef9085fb9507"
  _type = "messages/Injury"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32   trauma_head
int32   trauma_torso
int32   trauma_lower_ext
int32   trauma_upper_ext
int32   trauma_ocular
int32   alertness_ocular
int32   alertness_verbal
int32   alertness_motor"""
  __slots__ = ['trauma_head','trauma_torso','trauma_lower_ext','trauma_upper_ext','trauma_ocular','alertness_ocular','alertness_verbal','alertness_motor']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       trauma_head,trauma_torso,trauma_lower_ext,trauma_upper_ext,trauma_ocular,alertness_ocular,alertness_verbal,alertness_motor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Injury, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.trauma_head is None:
        self.trauma_head = 0
      if self.trauma_torso is None:
        self.trauma_torso = 0
      if self.trauma_lower_ext is None:
        self.trauma_lower_ext = 0
      if self.trauma_upper_ext is None:
        self.trauma_upper_ext = 0
      if self.trauma_ocular is None:
        self.trauma_ocular = 0
      if self.alertness_ocular is None:
        self.alertness_ocular = 0
      if self.alertness_verbal is None:
        self.alertness_verbal = 0
      if self.alertness_motor is None:
        self.alertness_motor = 0
    else:
      self.trauma_head = 0
      self.trauma_torso = 0
      self.trauma_lower_ext = 0
      self.trauma_upper_ext = 0
      self.trauma_ocular = 0
      self.alertness_ocular = 0
      self.alertness_verbal = 0
      self.alertness_motor = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.trauma_head, _x.trauma_torso, _x.trauma_lower_ext, _x.trauma_upper_ext, _x.trauma_ocular, _x.alertness_ocular, _x.alertness_verbal, _x.alertness_motor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.trauma_head, _x.trauma_torso, _x.trauma_lower_ext, _x.trauma_upper_ext, _x.trauma_ocular, _x.alertness_ocular, _x.alertness_verbal, _x.alertness_motor,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.trauma_head, _x.trauma_torso, _x.trauma_lower_ext, _x.trauma_upper_ext, _x.trauma_ocular, _x.alertness_ocular, _x.alertness_verbal, _x.alertness_motor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.trauma_head, _x.trauma_torso, _x.trauma_lower_ext, _x.trauma_upper_ext, _x.trauma_ocular, _x.alertness_ocular, _x.alertness_verbal, _x.alertness_motor,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
