# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from messages/Remaining_reports.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import messages.msg

class Remaining_reports(genpy.Message):
  _md5sum = "d18ac92b88307708af88871aae17ed91"
  _type = "messages/Remaining_reports"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Critical    critical
Vitals      vitals 
Injury      injury
================================================================================
MSG: messages/Critical
int32   hemorrhage
int32   distress
================================================================================
MSG: messages/Vitals
int32 heart
int32 respiratory
================================================================================
MSG: messages/Injury
int32   trauma_head
int32   trauma_torso
int32   trauma_lower_ext
int32   trauma_upper_ext
int32   trauma_ocular
int32   alertness_ocular
int32   alertness_verbal
int32   alertness_motor"""
  __slots__ = ['critical','vitals','injury']
  _slot_types = ['messages/Critical','messages/Vitals','messages/Injury']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       critical,vitals,injury

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Remaining_reports, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.critical is None:
        self.critical = messages.msg.Critical()
      if self.vitals is None:
        self.vitals = messages.msg.Vitals()
      if self.injury is None:
        self.injury = messages.msg.Injury()
    else:
      self.critical = messages.msg.Critical()
      self.vitals = messages.msg.Vitals()
      self.injury = messages.msg.Injury()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12i().pack(_x.critical.hemorrhage, _x.critical.distress, _x.vitals.heart, _x.vitals.respiratory, _x.injury.trauma_head, _x.injury.trauma_torso, _x.injury.trauma_lower_ext, _x.injury.trauma_upper_ext, _x.injury.trauma_ocular, _x.injury.alertness_ocular, _x.injury.alertness_verbal, _x.injury.alertness_motor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.critical is None:
        self.critical = messages.msg.Critical()
      if self.vitals is None:
        self.vitals = messages.msg.Vitals()
      if self.injury is None:
        self.injury = messages.msg.Injury()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.critical.hemorrhage, _x.critical.distress, _x.vitals.heart, _x.vitals.respiratory, _x.injury.trauma_head, _x.injury.trauma_torso, _x.injury.trauma_lower_ext, _x.injury.trauma_upper_ext, _x.injury.trauma_ocular, _x.injury.alertness_ocular, _x.injury.alertness_verbal, _x.injury.alertness_motor,) = _get_struct_12i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12i().pack(_x.critical.hemorrhage, _x.critical.distress, _x.vitals.heart, _x.vitals.respiratory, _x.injury.trauma_head, _x.injury.trauma_torso, _x.injury.trauma_lower_ext, _x.injury.trauma_upper_ext, _x.injury.trauma_ocular, _x.injury.alertness_ocular, _x.injury.alertness_verbal, _x.injury.alertness_motor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.critical is None:
        self.critical = messages.msg.Critical()
      if self.vitals is None:
        self.vitals = messages.msg.Vitals()
      if self.injury is None:
        self.injury = messages.msg.Injury()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.critical.hemorrhage, _x.critical.distress, _x.vitals.heart, _x.vitals.respiratory, _x.injury.trauma_head, _x.injury.trauma_torso, _x.injury.trauma_lower_ext, _x.injury.trauma_upper_ext, _x.injury.trauma_ocular, _x.injury.alertness_ocular, _x.injury.alertness_verbal, _x.injury.alertness_motor,) = _get_struct_12i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12i = None
def _get_struct_12i():
    global _struct_12i
    if _struct_12i is None:
        _struct_12i = struct.Struct("<12i")
    return _struct_12i
