// Generated by gencpp from file messages/Critical.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_CRITICAL_H
#define MESSAGES_MESSAGE_CRITICAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct Critical_
{
  typedef Critical_<ContainerAllocator> Type;

  Critical_()
    : hemorrhage(0)
    , distress(0)  {
    }
  Critical_(const ContainerAllocator& _alloc)
    : hemorrhage(0)
    , distress(0)  {
  (void)_alloc;
    }



   typedef int32_t _hemorrhage_type;
  _hemorrhage_type hemorrhage;

   typedef int32_t _distress_type;
  _distress_type distress;





  typedef boost::shared_ptr< ::messages::Critical_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::Critical_<ContainerAllocator> const> ConstPtr;

}; // struct Critical_

typedef ::messages::Critical_<std::allocator<void> > Critical;

typedef boost::shared_ptr< ::messages::Critical > CriticalPtr;
typedef boost::shared_ptr< ::messages::Critical const> CriticalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::Critical_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::Critical_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::Critical_<ContainerAllocator1> & lhs, const ::messages::Critical_<ContainerAllocator2> & rhs)
{
  return lhs.hemorrhage == rhs.hemorrhage &&
    lhs.distress == rhs.distress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::Critical_<ContainerAllocator1> & lhs, const ::messages::Critical_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::messages::Critical_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Critical_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Critical_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Critical_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Critical_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Critical_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::Critical_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b92d3e2e62f03348662932b496ff104";
  }

  static const char* value(const ::messages::Critical_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b92d3e2e62f0334ULL;
  static const uint64_t static_value2 = 0x8662932b496ff104ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::Critical_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/Critical";
  }

  static const char* value(const ::messages::Critical_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::Critical_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32   hemorrhage\n"
"int32   distress\n"
;
  }

  static const char* value(const ::messages::Critical_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::Critical_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hemorrhage);
      stream.next(m.distress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Critical_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::Critical_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::Critical_<ContainerAllocator>& v)
  {
    s << indent << "hemorrhage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hemorrhage);
    s << indent << "distress: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_CRITICAL_H
